#!/bin/bash
echo "--Deploy script started--"
echo "...Removing previous build folder"
STAMP=$(date +%s)
PACKAGE_NAME="package_samd-femtoio-build-$STAMP"
rm -fR package_*
echo "...Making new build folder"
mkdir "$PACKAGE_NAME"
echo "...Copying into build folder"
cp -R bootloaders "$PACKAGE_NAME/bootloaders"
cp -R cores "$PACKAGE_NAME/cores"
cp -R extras "$PACKAGE_NAME/extras"
cp -R libraries "$PACKAGE_NAME/libraries"
cp -R variants "$PACKAGE_NAME/variants"
cp CHANGELOG "$PACKAGE_NAME/CHANGELOG"
cp README.md "$PACKAGE_NAME/README.md"
cp boards.txt "$PACKAGE_NAME/boards.txt"
cp platform.txt "$PACKAGE_NAME/platform.txt"
cp programmers.txt "$PACKAGE_NAME/programmers.txt"
echo "Compressing archive (*.tar.bz2)"
tar -jcvf "$PACKAGE_NAME.tar.bz2" "$PACKAGE_NAME"
echo "Copying archive to ../Arduino-LocalTestRepo"
cp "$PACKAGE_NAME.tar.bz2" "../Arduino-LocalTestRepo/"
echo "--------------------"
echo "Update your package_*_index.json file at ../Arduino-LocalTestRepo/ with the following:"
FILESIZE=$(stat -c%s $PACKAGE_NAME.tar.bz2)
CHECKSUM=$(sha256sum $PACKAGE_NAME.tar.bz2)
echo ""
echo "Archive name is $PACKAGE_NAME.tar.bz2"
echo "File size (bytes) is $FILESIZE"
echo "Checksum is SHA-256:$CHECKSUM";
echo "---OK---"
