; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
framework = arduino
lib_deps = 
	arduino-libraries/Arduino_MKRIoTCarrier@^2.1.0
	arduino-libraries/WiFiNINA@^1.8.14
	arduino-libraries/ArduinoHttpClient@^0.6.1
	bblanchon/ArduinoJson@^7.2.0
lib_ignore = 
	MKRGSM
	MKRNB
	MKRWAN
	Blues Wireless Notecard
	Arduino_KVStore
	Arduino_NetworkConfigurator
