
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -1;
const int acc_off_y = 735;
const int acc_off_z = -1038;
const float acc_scale_x = 14656.995164;
const float acc_scale_y = 18711.392922;
const float acc_scale_z = 17720.881272;

const int magn_off_x = -212;
const int magn_off_y = -104;
const int magn_off_z = 368;
const float magn_scale_x = 177.686592;
const float magn_scale_y = 282.400653;
const float magn_scale_z = 642.611914;
