
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 887;
const int acc_off_y = 486;
const int acc_off_z = 2184;
const float acc_scale_x = 16075.288895;
const float acc_scale_y = 16695.714640;
const float acc_scale_z = 16643.954947;

const int magn_off_x = -183;
const int magn_off_y = -123;
const int magn_off_z = 370;
const float magn_scale_x = 232.614631;
const float magn_scale_y = 290.821213;
const float magn_scale_z = 402.295235;
