
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 878;
const int acc_off_y = 261;
const int acc_off_z = 505;
const float acc_scale_x = 15687.435723;
const float acc_scale_y = 16984.641645;
const float acc_scale_z = 16915.769739;

const int magn_off_x = -103;
const int magn_off_y = 74;
const int magn_off_z = 240;
const float magn_scale_x = 258.898633;
const float magn_scale_y = 260.198092;
const float magn_scale_z = 278.550384;
