
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -1286;
const int acc_off_y = 136;
const int acc_off_z = -540;
const float acc_scale_x = 16812.203304;
const float acc_scale_y = 16256.302325;
const float acc_scale_z = 16726.019955;

const int magn_off_x = -98;
const int magn_off_y = 435;
const int magn_off_z = -1457;
const float magn_scale_x = 6175.704237;
const float magn_scale_y = 5960.673982;
const float magn_scale_z = 5819.393546;
