
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -15;
const int acc_off_y = -9;
const int acc_off_z = -12;
const float acc_scale_x = 251.168382;
const float acc_scale_y = 264.747381;
const float acc_scale_z = 250.920777;

const int magn_off_x = -2;
const int magn_off_y = -96;
const int magn_off_z = -5;
const float magn_scale_x = 517.837841;
const float magn_scale_y = 497.261436;
const float magn_scale_z = 490.183062;
