
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 385;
const int acc_off_y = 176;
const int acc_off_z = 12;
const float acc_scale_x = 16286.628816;
const float acc_scale_y = 16454.226280;
const float acc_scale_z = 16529.735185;

const int magn_off_x = 31;
const int magn_off_y = -93;
const int magn_off_z = 36;
const float magn_scale_x = 475.995679;
const float magn_scale_y = 495.853226;
const float magn_scale_z = 507.326325;
