
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 112;
const int acc_off_y = 370;
const int acc_off_z = 1562;
const float acc_scale_x = 15859.162622;
const float acc_scale_y = 16076.831242;
const float acc_scale_z = 16679.336963;

const int magn_off_x = 210;
const int magn_off_y = 259;
const int magn_off_z = 657;
const float magn_scale_x = 2885.187579;
const float magn_scale_y = 2982.692806;
const float magn_scale_z = 2810.079487;
