
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 103;
const int acc_off_y = 374;
const int acc_off_z = 1597;
const float acc_scale_x = 15901.875411;
const float acc_scale_y = 16072.316296;
const float acc_scale_z = 16692.581185;

const int magn_off_x = 577;
const int magn_off_y = 529;
const int magn_off_z = 1558;
const float magn_scale_x = 5915.427902;
const float magn_scale_y = 6032.747415;
const float magn_scale_z = 5611.267290;
