
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 13;
const int acc_off_y = 5;
const int acc_off_z = -16;
const float acc_scale_x = 249.766474;
const float acc_scale_y = 284.155248;
const float acc_scale_z = 259.154216;

const int magn_off_x = 72;
const int magn_off_y = -109;
const int magn_off_z = 85;
const float magn_scale_x = 625.652682;
const float magn_scale_y = 551.447518;
const float magn_scale_z = 501.959832;
