
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 100;
const int acc_off_y = 38;
const int acc_off_z = 1694;
const float acc_scale_x = 16371.667083;
const float acc_scale_y = 16495.350321;
const float acc_scale_z = 16581.985398;

const int magn_off_x = 37;
const int magn_off_y = -122;
const int magn_off_z = -1;
const float magn_scale_x = 525.373957;
const float magn_scale_y = 492.116968;
const float magn_scale_z = 456.674712;
