
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 54;
const int acc_off_y = -112;
const int acc_off_z = -83;
const float acc_scale_x = 16325.833529;
const float acc_scale_y = 16372.621904;
const float acc_scale_z = 16360.376226;

const int magn_off_x = -32;
const int magn_off_y = -1;
const int magn_off_z = 10;
const float magn_scale_x = 90.689360;
const float magn_scale_y = 137.557678;
const float magn_scale_z = 129.254897;
