
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -13;
const int acc_off_y = 54;
const int acc_off_z = 1670;
const float acc_scale_x = 16473.201581;
const float acc_scale_y = 16476.242591;
const float acc_scale_z = 16539.453298;

const int magn_off_x = 18;
const int magn_off_y = -120;
const int magn_off_z = -14;
const float magn_scale_x = 526.703759;
const float magn_scale_y = 495.151070;
const float magn_scale_z = 450.137734;
