
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 118;
const int acc_off_y = -20;
const int acc_off_z = 655;
const float acc_scale_x = 16444.451002;
const float acc_scale_y = 16427.443205;
const float acc_scale_z = 16520.341389;

const int magn_off_x = 25;
const int magn_off_y = -114;
const int magn_off_z = -2;
const float magn_scale_x = 524.472425;
const float magn_scale_y = 493.912846;
const float magn_scale_z = 447.515283;
