
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -14;
const int acc_off_y = -7;
const int acc_off_z = -18;
const float acc_scale_x = 235.422159;
const float acc_scale_y = 260.299295;
const float acc_scale_z = 252.196241;

const int magn_off_x = -25;
const int magn_off_y = -39;
const int magn_off_z = 3;
const float magn_scale_x = 515.549930;
const float magn_scale_y = 489.638243;
const float magn_scale_z = 485.275307;
