
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 348;
const int acc_off_y = -185;
const int acc_off_z = -700;
const float acc_scale_x = 16339.684276;
const float acc_scale_y = 16440.691292;
const float acc_scale_z = 16734.635623;

const int magn_off_x = 110;
const int magn_off_y = -20;
const int magn_off_z = 98;
const float magn_scale_x = 562.527189;
const float magn_scale_y = 512.592944;
const float magn_scale_z = 430.571178;
