
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 403;
const int acc_off_y = -74;
const int acc_off_z = -561;
const float acc_scale_x = 16322.333922;
const float acc_scale_y = 16376.575731;
const float acc_scale_z = 16591.109587;

const int magn_off_x = 111;
const int magn_off_y = 250;
const int magn_off_z = -49;
const float magn_scale_x = 486.815131;
const float magn_scale_y = 512.342835;
const float magn_scale_z = 437.208628;
