/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/24df92f2-5894-429e-9825-fad2b80ca6f1

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  int light;
  float pressure;
  float temperature;
  String weather_report;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this file.
*/

#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// Cloud variables
extern float humidity;
extern int light;
extern float pressure; 
extern float temperature;
extern String weather_report;

extern WiFiConnectionHandler ArduinoIoTPreferredConnection;

void initProperties();

void onHumidityChange();
void onLightChange();
void onPressureChange();
void onTemperatureChange();
void onWeatherReportChange();