/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled" 
  https://create.arduino.cc/cloud/things/24df92f2-5894-429e-9825-fad2b80ca6f1 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  int light;
  float pressure;
  float temperature;
  String weather_report;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this file.
*/

#include "thingProperties.h"

// Define cloud variables
float humidity = 0.0f;
int light = 0;
float pressure = 0.0f;
float temperature = 0.0f;
String weather_report = "";

// Initialize WiFi connection
WiFiConnectionHandler ArduinoIoTPreferredConnection(SECRET_SSID, SECRET_PASS);

void initProperties(){
  ArduinoCloud.setThingId(SECRET_DEVICE_KEY);
  ArduinoCloud.setDeviceId(SECRET_DEVICE_KEY);
  
  // Publish every 10 seconds (10000 ms) regardless of value changes
  ArduinoCloud.addProperty(humidity, Permission::Read).publishEvery(10 * SECONDS);
  ArduinoCloud.addProperty(light, Permission::Read).publishEvery(10 * SECONDS);
  ArduinoCloud.addProperty(pressure, Permission::Read).publishEvery(10 * SECONDS);
  ArduinoCloud.addProperty(temperature, Permission::Read).publishEvery(10 * SECONDS);
  ArduinoCloud.addProperty(weather_report, Permission::Read).publishEvery(10 * SECONDS);
}

void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}

void onLightChange()  {
  // Add your code here to act upon Light change
}

void onPressureChange()  {
  // Add your code here to act upon Pressure change
}

void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}

void onWeatherReportChange()  {
  // Add your code here to act upon WeatherReport change
}